name: docker

on:
  push:
    branches:
      - 'docker'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: mkuhlmann/mappointment:latest

  deploy-staging:
    needs:
      - docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Caprover Using GitHub Actions
        uses: dankore/github-to-caprover@v.1.0.6
        with:
          server: ${{ secrets.CAPROVER_URL }}
          password: ${{ secrets.CAPROVER_PASSWORD }}
          appName: ${{ secrets.CAPROVER_APP }}
          image: mkuhlmann/mappointment:latest
